.commit_comment:
  script:
    - export GITLAB_TOKEN="$PROJECT_ACCESS_TOKEN"
    - |
      commit_comment() {
        curl --location --request POST "https://git.amalgama.co/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/comments" --header "PRIVATE-TOKEN: $GITLAB_TOKEN" --header "Content-Type: application/json" --data-raw "{ \"note\": \"$1\" }"
      }

.mr_comment:
  script:
    - export GITLAB_TOKEN="$PROJECT_ACCESS_TOKEN"
    - |
      mr_comment() {
        curl --location --request POST "https://git.amalgama.co/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" --header "PRIVATE-TOKEN: $GITLAB_TOKEN" --header "Content-Type: application/json" --data-raw "{ \"body\": \"$1\" }"
      }