image: node:17.0.1

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: default
  CACHE_COMPRESSION_LEVEL: fast
  TRANSFER_METER_FREQUENCY: 5s

cache: &global_cache
  - key:
      files:
        - Gemfile.lock
      prefix: $CI_PROJECT_TITLE
    paths:
      - vendor/ruby
  - key:
      files:
        - yarn.lock
      prefix: $CI_PROJECT_TITLE
    paths:
      - node_modules/

before_script:
  - mkdir -p reports/

stages:
  - build
  - lint
  - test
  - docs
  - sonar

yarn:
  stage: build
  cache:
    untracked: true
  script:
    - yarn
  tags:
    - docker
  artifacts:
    paths:
      - reports/

run_linter:
  stage: lint
  cache:
    untracked: true
    policy: pull
  script:
    - yarn
    - yarn lint --no-error-on-unmatched-pattern
  tags:
    - docker

run_unit_tests:
  stage: test
  cache:
    untracked: true
    policy: pull
  script:
    - yarn
    - yarn test --ci --forceExit --passWithNoTests --detectOpenHandles
  tags:
    - docker
  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - reports/
    reports:
      junit:
        - reports/junit.xml
      cobertura: reports/coverage/cobertura-coverage.xml

upload_to_sonar:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sed -i.bk 's/SF:.*\/react-native-ui-kit\/\(.*\)/SF:\1/' reports/coverage/lcov.info
    - sonar-scanner
  allow_failure: true
  tags:
    - docker
  only:
    - master
    - develop
  dependencies:
    - run_unit_tests

pages:
  stage: docs
  script:
  - yarn
  - cd docs
  - yarn install
  - BASE_URL="/packages/npm/react-native-ui-kit/" yarn build
  - mv ./build ../public
  artifacts:
    paths:
    - public
  # only:
  #   - master
