image: node:17.0.1

include:
  - local: .functions.yml

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: default
  CACHE_COMPRESSION_LEVEL: fast
  TRANSFER_METER_FREQUENCY: 5s

cache: &global_cache
  - key:
      files:
        - yarn.lock
      prefix: $CI_PROJECT_TITLE
    paths:
      - node_modules/
  - key:
      files:
        - example/yarn.lock
      prefix: $CI_PROJECT_TITLE
    paths:
      - example/node_modules/
  - key:
      files:
        - web_example/yarn.lock
      prefix: $CI_PROJECT_TITLE
    paths:
      - web_example/node_modules/
  - key:
      files:
        - docs/yarn.lock
      prefix: $CI_PROJECT_TITLE
    paths:
      - docs/node_modules/

before_script:
  - mkdir -p reports/

stages:
  - build
  - lint
  - test
  - docs
  - sonar

yarn:
  stage: build
  cache:
    untracked: true
  script:
    - yarn
  tags:
    - docker
  artifacts:
    paths:
      - reports/

run_linter:
  stage: lint
  cache:
    untracked: true
    policy: pull
  script:
    - yarn
    - yarn lint --no-error-on-unmatched-pattern
  tags:
    - docker

run_unit_tests:
  stage: test
  cache:
    untracked: true
    policy: pull
  script:
    - yarn
    - yarn test --ci --forceExit --passWithNoTests --detectOpenHandles
  tags:
    - docker
  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - reports/
    reports:
      junit:
        - reports/junit.xml
      cobertura: reports/coverage/cobertura-coverage.xml

upload_to_sonar:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sed -i.bk 's/SF:.*\/embassy-ui\/\(.*\)/SF:\1/' reports/coverage/lcov.info
    - sonar-scanner
  allow_failure: true
  tags:
    - docker
  only:
    - main
  dependencies:
    - run_unit_tests

preview_docs:
  stage: docs
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - docs/**/*
      allow_failure: true
  before_script:
    - apt-get update -qqy && apt-get install -qqy awscli
  script:
    - yarn
    - cd docs
    - yarn install
    - URL=$DOCS_PREVIEW_BASE_URL BASE_URL="/${CI_COMMIT_SHORT_SHA}/" yarn build
    - aws s3 sync build "${DOCS_PREVIEW_BUCKET_PATH}/${CI_COMMIT_SHORT_SHA}/"
    - !reference [.mr_comment, script]
    - mr_comment "You can see a preview of the changes made to the docs [here](${DOCS_PREVIEW_BASE_URL}/${CI_COMMIT_SHORT_SHA}/)"

pages:
  stage: docs
  script:
    - yarn
    - cd docs
    - yarn install
    - yarn build
    - mv ./build ../public
  artifacts:
    paths:
      - public
  only:
    - main
