on:
  release:
    types: [published]

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: yarn ci
    - run: URL="$DOCS_PRODUCTION_BASE_URL" yarn docs build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.DOCS_PRODUCTION_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'docs/build'
    - uses: chetan/invalidate-cloudfront-action@v2
      env:
        PATHS: "/index.html"
        AWS_REGION: "us-east-1"
        DISTRIBUTION: ${{ secrets.DOCS_PRODUCTION_AWS_CLOUDFRONT_DISTRIBUTION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}