name: Docs Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**/*'

jobs:
  deploy_docs_preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: yarn ci
    - run: URL="$DOCS_PREVIEW_BASE_URL" BASE_URL="/${GITHUB_SHA}/" yarn docs build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.DOCS_PREVIEW_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'docs/build'
        DEST_DIR: ${{ github.sha }}
    - uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          You can see a preview of the changes made to the docs [here](${{ secrets.DOCS_PREVIEW_BASE_URL }}/${{ github.sha }})